theme: jekyll-theme-minima
title: Matthias Droth's Homepage
description: Bookmark this to keep an eye on my project updates!
# list possible themes:
#   Architect
#   Cayman
#   Dinky
#   Hacker
#   Leap day
#   Merlot
#   Midnight
#   Minima
#   Minimal
#   Modernist
#   Slate
#   Tactile
#   Time machine
